// AUTO-GENERATED by scripts/generate-locales.ts — DO NOT EDIT.
// Regenerate with: bun run locales:generate
import type { Translation } from './types';
import da from './locales/da/translation.json';
import de from './locales/de/translation.json';
import en from './locales/en/translation.json';
import es from './locales/es/translation.json';
import fr from './locales/fr/translation.json';
import hu from './locales/hu/translation.json';
import it from './locales/it/translation.json';
import nl from './locales/nl/translation.json';
import pl from './locales/pl/translation.json';
import pt from './locales/pt/translation.json';
import ru from './locales/ru/translation.json';
import sk from './locales/sk/translation.json';
import sr from './locales/sr/translation.json';

export type SupportedLanguage = 'da' | 'de' | 'en' | 'es' | 'fr' | 'hu' | 'it' | 'nl' | 'pl' | 'pt' | 'ru' | 'sk' | 'sr';

export const translations: Record<SupportedLanguage, Translation> = {
  da: da as unknown as Translation,
  de: de as unknown as Translation,
  en: en as unknown as Translation,
  es: es as unknown as Translation,
  fr: fr as unknown as Translation,
  hu: hu as unknown as Translation,
  it: it as unknown as Translation,
  nl: nl as unknown as Translation,
  pl: pl as unknown as Translation,
  pt: pt as unknown as Translation,
  ru: ru as unknown as Translation,
  sk: sk as unknown as Translation,
  sr: sr as unknown as Translation
};
